@clientToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZW1weSIsImlkIjoiMDFKUlc0U0hFRFEzTlRITlAwWkRKNktXMzIiLCJyb2xlIjpbIkFETUlOIl0sImF1dGgiOiJDTElFTlQiLCJjb2RlIjoidG1wIiwiZXhwIjoxNzUxNDMwNjA3fQ.bFAZZgfvSqHsybFTjhKqGLAqmNkyrQvtyF4d2ChD6jI
@token = {{clientToken}}

### Get Root
GET http://localhost:1877/
Accept: application/json


### Get Health Check
GET http://localhost:1877/health
Accept: application/json


### POST Convert Document with OCR disabled (Default) /home/skyfy/Downloads/UUD1945.pdf /home/skyfy/Downloads/UU Nomor 1 Tahun 2023.pdf
POST http://localhost:1877/api/v1/convert
authorization: {{token}}
Content-Type: multipart/form-data; boundary=_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z

--_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="file"; filename="UUD1945.pdf"

< /home/skyfy/Downloads/UUD1945.pdf
--_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="enable_ocr"

false
--_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="output_type"

markdown
--_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z--


### POST Convert and Chunk Document with OCR enabled
POST http://localhost:1877/api/v1/convert_n_chunk
authorization: {{token}}
Content-Type: multipart/form-data; boundary=Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z

--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="file"; filename="UUD1945.pdf"

< /home/skyfy/Downloads/UUD1945.pdf
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="enable_ocr"

true
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="ocr_langs"

id
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="max_tokens"

1024
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="output_type"

json
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="chunk_type"

recursive_text
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z--