@clientToken = Bearer p1Ho11H3RtWiyTqfdcHSBzxcBdXdedAlb2SknB7SIQs=
@token = {{clientToken}}
@server_host=https://docling.gai.co.id/
@local_host=http://localhost:1877/
@host={{local_host}}


### Get Root
GET {{host}}
Accept: application/json


### Get Health Check
GET {{host}}health
Accept: application/json


### POST Convert Document with OCR disabled (Default) /home/skyfy/Downloads/UUD1945.pdf /home/skyfy/Downloads/UU Nomor 1 Tahun 2023.pdf
POST {{host}}api/v1/convert
authorization: {{token}}
Content-Type: multipart/form-data; boundary=_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z

--_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="file"; filename="UUD1945.pdf"

< /home/skyfy/Downloads/UUD1945.pdf
--_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="enable_ocr"

false
--_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="output_type"

markdown
--_k3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z--


### POST Convert and Chunk Document with OCR enabled
POST {{host}}api/v1/convert_n_chunk
authorization: {{token}}
Content-Type: multipart/form-data; boundary=Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z

--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="file"; filename="UUD1945.pdf"

< /home/skyfy/Downloads/UUD1945.pdf
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="enable_ocr"

true
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="ocr_langs"

id
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="max_tokens"

1024
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="output_type"

json
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z
Content-Disposition: form-data; name="chunk_type"

recursive_text
--Ck3m6e-jha83GLt1mB0L2oZpP8kqTDn3AyE7z--